### ISSUE TITLE
Gameplay fixes

### ISSUE THREAD

**Issue by ZxGanon** [DoGyAUT/cd#11]
Global:
- Green LAT slows units (bug)
- Tanks (like Archon Tanks) do not crush Sandbag-Walls (bug)
- Fire damage against Aircraft from 25 to 100

GDI:
-    Medic need to require Radar
-    Grizzly Tank 122mm Weapon attackspeed from 200 to 140 and Grizzly from 1300$ to 1400$
-    Give Hornet same Anti Air attack range that Firehawk has (look at the new Firehawk values)

Nod: 
-    Propaganda Confessor should require Tech Pyramid instead of Radar
-    Banshee MKII to be more like in Tiberium Sun, Costs from 2250$ to 1800$, Shall use Tiberium Balls, 
     3 Green balls as ammunition (or maybe you got a better idea), Can only attack ground (for now)
-    Raven shall inhire Firedamage, Raven needs flame visual for its new purpose as a Mig and also
      visuals and burn damage, upgraded with blue hell inferno + new visuals
-    Stealth Tank might benefit from EMP Rocket System on T3 Upgradelevel
-    Gorran instead of an MG give him a rocket to function like GLA Scorpion, receives Tiberium Warhead
      Upgrade on T3 for this Rocket
-    Might prefer to keep the 3 missile burst for Technology and Propaganda Nod to make it different
      from GDI Sam
-    Raider Buggy from Technology Nod shall receive Lasers on T3 upgrade can also attack air with that
      laser

Forgotten:
- Bounty Hunter shall attack air(all) with his rockets
- Make Buzzard equipable with 2-3 different weapontypes (same principle like vehicle)

**Comment by DoGyAUT** [comment]
Banshee and Buzzard are the only ones left from this list not done.

**Comment by ZxGanon** [comment]
GJ!
