### ISSUE TITLE
Incorrect hit-shapes and TargetableOffsets

### ISSUE THREAD

**Issue by CDVoidwalker** [DoGyAUT/cd#113]
![image](https://user-images.githubusercontent.com/25931859/27176762-2b46a27e-51c4-11e7-8c46-972495be7b27.png)

**Comment by rob-v** [comment]
I assume it is related to/fixed by this PR https://github.com/OpenRA/OpenRA/pull/13464

**Comment by GraionDilach** [comment]
Related to, but won't be fixed by.
