### ISSUE TITLE
Orca Scout Crash

### ISSUE THREAD

**Issue by CDVoidwalker** [DoGyAUT/cd#14]
`Crystallized Doom Mod at Version Closed Beta
on map bef0864da9ae3934e3fd92849ab976417f238c17 (Tournament Rift 1.5 by ZxGanon).
Date: 2017-02-25 16:24:24Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.ArgumentNullException`: Wartość nie może być zerowa.
Nazwa parametru: key
   w System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   w System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   w OpenRA.ReadOnlyDictionary`2.TryGetValue(TKey key, TValue& value) w d:\OpenRA\OpenRA.Game\Primitives\ReadOnlyDictionary.cs:wiersz 73
   w OpenRA.Graphics.SequenceProvider.GetSequence(String unitName, String sequenceName) w d:\OpenRA\OpenRA.Game\Graphics\SequenceProvider.cs:wiersz 76
   w OpenRA.Graphics.Animation.GetSequence(String sequenceName) w d:\OpenRA\OpenRA.Game\Graphics\Animation.cs:wiersz 206
   w OpenRA.Graphics.Animation.PlaySequence(String sequenceName) w d:\OpenRA\OpenRA.Game\Graphics\Animation.cs:wiersz 87
   w OpenRA.Graphics.Animation.PlayFetchIndex(String sequenceName, Func`1 func) w d:\OpenRA\OpenRA.Game\Graphics\Animation.cs:wiersz 146
   w OpenRA.Mods.Common.Effects.Beacon..ctor(Player owner, WPos position, Boolean isPlayerPalette, String palette, String posterCollection, String posterType, String posterPalette, String arrowSequence, String circleSequence, String clockSequence, Func`1 clockFraction, Int32 delay, Int32 duration)
   w OpenRA.Mods.Common.Traits.AirstrikePower.<>c__DisplayClassf.<SendAirstrike>b__d(World w)
   w OpenRA.World.Tick() w d:\OpenRA\OpenRA.Game\World.cs:wiersz 350
   w OpenRA.Game.InnerLogicTick(OrderManager orderManager) w d:\OpenRA\OpenRA.Game\Game.cs:wiersz 587
   w OpenRA.Game.LogicTick() w d:\OpenRA\OpenRA.Game\Game.cs:wiersz 611
   w OpenRA.Game.Loop() w d:\OpenRA\OpenRA.Game\Game.cs:wiersz 738
   w OpenRA.Game.Run() w d:\OpenRA\OpenRA.Game\Game.cs:wiersz 778
   w OpenRA.Program.Run(String[] args) w d:\OpenRA\OpenRA.Game\Support\Program.cs:wiersz 133
   w OpenRA.Program.Main(String[] args) w d:\OpenRA\OpenRA.Game\Support\Program.cs:wiersz 40

`

**Comment by GraionDilach** [comment]
Caused by https://github.com/OpenRA/OpenRA/pull/12751. Include the old default values in the yaml.

**Comment by ZxGanon** [comment]
All Supportpowers crash the game. Propaganda Frenzy Ability aswell.

**Comment by GraionDilach** [comment]
All are due to the PR I linked.

**Comment by CDVoidwalker** [comment]
disabled gdi support powers for now
