### ISSUE TITLE
Tiberium glow near edge of the screen

### ISSUE THREAD

**Issue by jrb0001** [DoGyAUT/cd#15]
The tiberium glow isn't rendered if the crystal is outside the screen.

**Comment by jrb0001** [comment]
The same is true for light posts.

**Comment by DoGyAUT** [comment]
I think it's how OpenRA does the rendering, it's the same for trees as example.

**Comment by GraionDilach** [comment]
You can change renderbounds for fixing this, however, A good example case are tunnel tops which technically only occupies the middle tunnel top cell.

**Comment by GraionDilach** [comment]
The bleed update should have included the rendering refactors which should deal with this one.

**Comment by jrb0001** [comment]
Yes, this is fixed now.
