### ISSUE TITLE
Overhaul of Prerequisites

### ISSUE THREAD

**Issue by ZxGanon** [DoGyAUT/cd#18]
**Buildings:**
Power Plant => nothing
Refinery => Power Plant
Barracks => Power Plant
War Factory => Power Plant, Refinery
Radar => Power Plant, Refinery
GDI Armory => Power Plant, Radar
Helipad => Power Plant, GDI Radar
GDI Service Depot => Power Plant, War Factory
GDI Tech Center => Power Plant, Radar, Armory
Nod Pyramid => Power Plant/Advanced Power Plant, Radar
Cabal Cyborg Enhancement Center => Power Core, Radar
Forgotten Trade Post => Power Plant, Clan Hovel, Radar
Steel Talon Dropship-Bay => Power Plant, Armory, Steel Talon Upgrade, Tech Center
Clan Hovel => Power Plant, Refinery

**Defense:**
Concrete Wall => nothing
Gate => nothing
Vulcan Tower, Sabercut, Watch Tower => Power Plant, Barracks
Flamer Turret => Technology/Propaganda Nod Upgrade, Power Plant, Barracks
Gatling Tower => Industry Nod Upgrade, Power Plant, Barracks
Sniper-Sensor Tower, Laser Turret, Plasma Blaster, Gecko Launcher => Power Plant, Barracks, Radar
Talon Tower => Power Plant, Barracks, Steel Talon Upgrade 
SAM Tower, Obelisk of Darkness, Flak Cannon => Power Plant, Barracks, Radar
SAM Site => Technology/Propaganda Nod Upgrade, Power Plant, Barracks, Radar
Fortress Garrision Bunker => Power Plant, Barracks, Armory, GDF Upgrade
Howitzer Tower => Power Plant, Barracks, Armory, GDF Upgrade, Tech Center
Guardian Tower, Obelisk of Light, Core Obelisk => Power Plant, Barracks, Tech Center
GDI Upgrade Center => Power Plant, Tech Center
Ion Cannon Uplink => Power Plant, Upgrade Center
E.M. Pulse Cannon => Technology Nod Upgrade, Power Plant, Nod Pyramid
Fortress Artillery Bunker => Power Plant, Armory, GDF Upgrade, Tech Center
Stealth Generator => Technology Nod Upgrade, Power Plant, Nod Pyramid 
Temple of Nod => Propaganda Nod Upgrade, Power Plant, Nod Pyramid
Nod Missile Silo => Industry Nod Upgrade, Power Plant, Nod Pyramid

**Infantry:**

**Comment by DoGyAUT** [comment]
More details would be nice.

**Comment by CDVoidwalker** [comment]
To be fair, we literally have to take look at everything and list it, as most of the stuff is wrong anyways >.>

**Comment by CDVoidwalker** [comment]
done
