### ISSUE TITLE
Discord: The instant invite is invalid or has expired.

### ISSUE THREAD

**Issue by Mailaender** [DoGyAUT/cd#2]
> Discord Chat: https://discord.gg/0rCjz5ayxKUqtlGO

from https://github.com/DoGyAUT/cd/blob/master/README.md

:cry:

**Comment by DoGyAUT** [comment]
Oh seems that link has indeed expired,

here is a new one for you :)
https://discord.gg/zZUBRvF

Latest available version on discord is based on two month old ORA bleed.

The next update includes an updated ORA and AS.dll support (scheduled for next week).

**Comment by DoGyAUT** [comment]
I updated the readme with a new link.
