### ISSUE TITLE
Fixes!

### ISSUE THREAD

**Issue by ZxGanon** [DoGyAUT/cd#28]
- Stealth Generator - from 2000$ to 1500$, from 200 to 150 Energy
- Hi Tech buildings like Hospital and Armory can be sold - crashes the game
- Watch Tower sound is too loud
- Reckoner Bug - only 1 unit shoots out of it and with weapon upgrades nothing does
- Increase aircraft husk damage
- Devils Tongue from 1000$ to 1400$
- huntress more hp
- APC weapon to HE and double the damage Armament@Cannon
- increase TiberiumObelisk spread
- change visceroid (more hp, less movementspeed, a bit less damage)
- Rocketeer cost to 250$
- Confessor M203 to HEWH
- fixing stealth tank
- zone raider aa damage cut in half ZRaiderBazooka
- cannon husk to 300$
- Digger_Mis (Digger with Missiles) cannot move
- stealth tank nerf damage and upgrade damage StealthDragon, StealthDragonEMP
- change mammoth tank to burst 120mm1+2
- change selfregenerating to be slower but to 100% full health
- look at all chassis
- auroch 120mm twincannon needs little attackspeed buff
- hailstorm hewh: Stormdragon
- specter apwh: 155mm, 155mmEMP, 155mmInferno
- juggernaut hewh: 180mmHE, 180mmHE2, 180mmHE3
- ragnarok heapwh: RagnarCannonCluster
- laser turret is bugged
- all 4 howitzer weapons: BuggyMortar (for Buggy and Truck), WarthogMortar, AurochMortar

**Comment by CDVoidwalker** [comment]
Note, Buzzard HEMissile might be too weak
