### ISSUE TITLE
Serious issues with eco due to harvesters

### ISSUE THREAD

**Issue by CDVoidwalker** [DoGyAUT/cd#29]
Only solution would be flattening all harvesters

**Comment by ZxGanon** [comment]
New Plan:
Global:
- all Harvestors carry 500$ cargo
- movementspeed to 50

Faction:
- GDI Harvestors stay tanky

Nod:
- Propaganda Harvestor gets tanky like GDI Harvestor
- Technology Harvestors stealths right from the start
- Industry Harvestors using Tiberium Weapon

 Forgotten:
- Receive an MG/Cannon

Cabal:
- Hovers

**Comment by jrb0001** [comment]
What about giving the Cabal harv double speed but halved cargo? Hover units are usually faster so that makes sense and the total money production speed should be about the same with those numbers.

Everything else sounds good to me.

**Comment by CDVoidwalker** [comment]
Should, but won't be as harvesters are randomly bouncing around with each other, blocking their way, etc. . And remember, too fast means that they can respond to enemy attacks way better than others anyway

**Comment by jrb0001** [comment]
The better responding to enemy attacks capabilities could be compensated by lowering the hp of the cabal harv a bit. Why should faster harvs randomly bounce around more with each other? I didn't see that yet.

**Comment by CDVoidwalker** [comment]
Simply put no, because people will cry that this harvester is weird / can be one shotted easily by bikes etc. I don't really want to touch them for now
