### ISSUE TITLE
Build instructions are outdated.

### ISSUE THREAD

**Issue by GraionDilach** [DoGyAUT/cd#3]
Since you base this upon the AS infrastructure now, you probably wouldwant to fork https://github.com/GraionDilach/OpenRA.Mods.AS and https://github.com/GraionDilach/OpenRA to have the commits CD is working on be accessible to people outside the internals, since I am force-pushing the latter.

Or you intend to maintain bleed sync this time?

**Comment by DoGyAUT** [comment]
Forked https://github.com/DoGyAUT/OpenRA.Mods.AS and https://github.com/DoGyAUT/OpenRA

**Comment by GraionDilach** [comment]
The readme still needs to be updated, however, so this was closed before it was completely fixed.
