### ISSUE TITLE
Civillian Armory extends short game

### ISSUE THREAD

**Issue by 0Freeicecream** [DoGyAUT/cd#32]
I'm assuming that tech structures aren't supposed to keep the standard short game rules going (Destroy enemy base), since the Tech Oil exploded on capture of the Civ Armory.

**Comment by CDVoidwalker** [comment]
fixed on my version

**Comment by 0Freeicecream** [comment]
Radar expansion does the same thing (Few games in Redzone Rampage have stalled because of this).  Don't know if you've got this one covered too.

**Comment by CDVoidwalker** [comment]
I've fixed it on all of civilian buildings
