### ISSUE TITLE
- AttackGarrisoned triggering only one weapon -

### ISSUE THREAD

**Issue by ZxGanon** [DoGyAUT/cd#33]
Reckoner unit inside cannot attack except one of them. If you upgrade weapon upgrade like BluHellInferno for Black Hand Flamer they not even a single Black Hand Flamer can shoot out of the Reckoner anymore.

**Comment by DoGyAUT** [comment]
All "AttackGarrisoned" are affected of this, most times only one entry seems to be able to attack. This is not actor depandand.

Trait probably has some unwanted codechange and might have not been noticed on regular RA as I am not aware of any actor which has more than 1 cargo in RA (Pillbox only).

This requires proper reserach.

**Comment by GraionDilach** [comment]
I have heard about this, but at this point I don't have a solution. The trait is complete bonkers and needs to be replaced in the long term with a trait which would shim the garrison armaments to the garrison actor from the passenger to be used along with regular attack traits.

**Comment by GraionDilach** [comment]
I believe this one has been fixed in OpenRA and the fix should have arrived to CD as well by now.
