### ISSUE TITLE
Energy usage by cabal units

### ISSUE THREAD

**Issue by jrb0001** [DoGyAUT/cd#38]
Cabal units should need energy to increase the difficulty for unit spam. Basic infantry should probably need ~1, the bigger tanks between 30 and 50 or even up to 100. If that makes them too expensive, reducing the cost for the power plants should solve that issue.

**Comment by jrb0001** [comment]
This really needs the power down button to prevent negative power after selling the whole base.

**Comment by ZxGanon** [comment]
Power Down Button will not find a way into this game anymore until it is absolute necessary ^^

**Comment by jrb0001** [comment]
Then you can close this issue.
