### ISSUE TITLE
UI crash with more than +5 production queues

### ISSUE THREAD

**Issue by DoGyAUT** [DoGyAUT/cd#4]
Currently the game crashes if you have more than 5 unique production queues. My guess is that the problem is caused by the missing queue scrollbar and icons. But I need further help here.

**Comment by GraionDilach** [comment]
Crashlog?

**Comment by CDVoidwalker** [comment]
`Crystallized Doom Mod at Version Closed Beta
on map 40b43b6a72688e3e270e6e70d18b721d5af74372 (Tournament Veil 1.1 by ZxGanon, Kyrylo).
Date: 2017-02-21 19:15:01Z
Operating System: Windows (Microsoft Windows NT 6.1.7601 Service Pack 1)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Odwołanie do obiektu nie zostało ustawione na wystąpienie obiektu.
   w OpenRA.Graphics.SpriteRenderer.DrawSprite(Sprite s, float3 location) w d:\OpenRA\OpenRA.Game\Graphics\SpriteRenderer.cs:wiersz 82
   w OpenRA.Widgets.WidgetUtils.DrawRGBA(Sprite s, float2 pos) w d:\OpenRA\OpenRA.Game\Widgets\WidgetUtils.cs:wiersz 28
   w OpenRA.Mods.Common.Widgets.ProductionTabsWidget.Draw()
   w OpenRA.Widgets.Widget.DrawOuter() w d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:wiersz 450
   w OpenRA.Widgets.Widget.DrawOuter() w d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:wiersz 452
   w OpenRA.Widgets.Widget.DrawOuter() w d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:wiersz 452
   w OpenRA.Widgets.Widget.DrawOuter() w d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:wiersz 452
   w OpenRA.Widgets.Widget.DrawOuter() w d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:wiersz 452
   w OpenRA.Widgets.Widget.DrawOuter() w d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:wiersz 452
   w OpenRA.Widgets.Widget.DrawOuter() w d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:wiersz 452
   w OpenRA.Widgets.Ui.Draw() w d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:wiersz 92
   w OpenRA.Game.RenderTick() w d:\OpenRA\OpenRA.Game\Game.cs:wiersz 609
   w OpenRA.Game.Loop() w d:\OpenRA\OpenRA.Game\Game.cs:wiersz 729
   w OpenRA.Game.Run() w d:\OpenRA\OpenRA.Game\Game.cs:wiersz 747
   w OpenRA.Program.Run(String[] args) w d:\OpenRA\OpenRA.Game\Support\Program.cs:wiersz 134
   w OpenRA.Program.Main(String[] args) w d:\OpenRA\OpenRA.Game\Support\Program.cs:wiersz 41

`

**Comment by DoGyAUT** [comment]
The crash happens when you switch the tabs.

`Crystallized Doom Mod at Version Closed Beta
on map bef0864da9ae3934e3fd92849ab976417f238c17 (Tournament Rift 1.5 by ZxGanon).
Date: 2017-02-21 20:06:55Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.NullReferenceException`: Der Objektverweis wurde nicht auf eine Objektinstanz festgelegt.
   bei OpenRA.Graphics.SpriteRenderer.DrawSprite(Sprite s, float3 location) in d:\OpenRA\OpenRA.Game\Graphics\SpriteRenderer.cs:Zeile 82.
   bei OpenRA.Widgets.WidgetUtils.DrawRGBA(Sprite s, float2 pos) in d:\OpenRA\OpenRA.Game\Widgets\WidgetUtils.cs:Zeile 28.
   bei OpenRA.Mods.Common.Widgets.ProductionTabsWidget.Draw()
   bei OpenRA.Widgets.Widget.DrawOuter() in d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 450.
   bei OpenRA.Widgets.Widget.DrawOuter() in d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 452.
   bei OpenRA.Widgets.Widget.DrawOuter() in d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 452.
   bei OpenRA.Widgets.Widget.DrawOuter() in d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 452.
   bei OpenRA.Widgets.Widget.DrawOuter() in d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 452.
   bei OpenRA.Widgets.Widget.DrawOuter() in d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 452.
   bei OpenRA.Widgets.Widget.DrawOuter() in d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 452.
   bei OpenRA.Widgets.Ui.Draw() in d:\OpenRA\OpenRA.Game\Widgets\Widget.cs:Zeile 92.
   bei OpenRA.Game.RenderTick() in d:\OpenRA\OpenRA.Game\Game.cs:Zeile 609.
   bei OpenRA.Game.Loop() in d:\OpenRA\OpenRA.Game\Game.cs:Zeile 729.
   bei OpenRA.Game.Run() in d:\OpenRA\OpenRA.Game\Game.cs:Zeile 747.
   bei OpenRA.Program.Run(String[] args) in d:\OpenRA\OpenRA.Game\Support\Program.cs:Zeile 134.
   bei OpenRA.Program.Main(String[] args) in d:\OpenRA\OpenRA.Game\Support\Program.cs:Zeile 41.

`

**Comment by GraionDilach** [comment]
I'll try to look into this around Sunday, I guess.

**Comment by GraionDilach** [comment]
Probably will be Monday now.

**Comment by DoGyAUT** [comment]
Don't have to stress it ofc.

**Comment by DoGyAUT** [comment]
https://github.com/DoGyAUT/cd/commit/a285ff0044fc6dcc290864e44d7d859c054348f6 fixes the crash.
