### ISSUE TITLE
New Ability for Marine (like GI from Ra2)

### ISSUE THREAD

**Issue by ZxGanon** [DoGyAUT/cd#41]
You could enable the ability of GIs from Ra2 for Marines to burrow and increase their range and damage.
If that finds its way to this game than we could increase the cost of Marines to 150$ or even 200$.

**Comment by GraionDilach** [comment]
That setup has a can of worms however - such a deploy would disable Mobile, resorting to use turrets for the deploying stage, but turrets don't have firing animation support at the moment IIRC, which is the reason why the ORA-RA2 mod lacks the GI deploy ability.

There is an issue with this for sure, but I don't remember what it was.

**Comment by GraionDilach** [comment]
NTM: `WithSpriteTurret` cannot support multiple Attack* traits  (required since deployed mode would switch to AttackTurreted from AttackFrontal) which is the issue I remembered.
