### ISSUE TITLE
Mod not starting

### ISSUE THREAD

**Issue by tglewis1993** [DoGyAUT/cd#75]
Followed the installation guide and got the following error log after running 'OpenRA.Game.exe Game.Mod=cd':

Date: 2017-05-14 16:07:52Z
Operating System: Windows (Microsoft Windows NT 6.2.9200.0)
Runtime Version: .NET CLR 4.0.30319.42000
Exception of type `System.IO.FileNotFoundException`: Assembly `as|OpenRA.Mods.AS.dll` not found.
   at OpenRA.ObjectCreator..ctor(Manifest manifest, InstalledMods mods) in e:\OpenRA-bleed\OpenRA.Game\ObjectCreator.cs:line 43
   at OpenRA.ModData..ctor(Manifest mod, InstalledMods mods, Boolean useLoadScreen) in e:\OpenRA-bleed\OpenRA.Game\ModData.cs:line 54
   at OpenRA.Game.InitializeMod(String mod, Arguments args) in e:\OpenRA-bleed\OpenRA.Game\Game.cs:line 370
   at OpenRA.Game.Initialize(Arguments args) in e:\OpenRA-bleed\OpenRA.Game\Game.cs:line 333
   at OpenRA.Program.Run(String[] args) in e:\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 131
   at OpenRA.Program.Main(String[] args) in e:\OpenRA-bleed\OpenRA.Game\Support\Program.cs:line 40

Could be doing something obviously wrong, and if so feel free to berate me if appropriate.

**Comment by j5bart** [comment]
You're not alone - I've had same issue. First time I've tried this process and thought I was doing something wrong too. Appreciate any advice from someone more in the know! :)

**Comment by tglewis1993** [comment]
It is from OpenRA.Mods.AS.dll being missing, but following the instructions in the readme doesn't appear to grab anything to do with AS... unless I've done it wrong...

**Comment by GraionDilach** [comment]
Which OS?

**Comment by tglewis1993** [comment]
Windows 10 64 Bit

**Comment by GraionDilach** [comment]
Okay, so if you compile the game through make all, do you get a mods/as folder with a dll in it?

**Comment by tglewis1993** [comment]
No, this folder is missing.

**Comment by GraionDilach** [comment]
Could you tell which config was compiled (check what subfolder is within OpenRA/OpenRA.Mods.AS/bin)?

I honestly never seen this issue, but I suspect the folder creation goes bonkers and the copying fails because of it. If I'm correct, creating the mods/as folder and then issuing the make all should work. Even then, I will look into a fix for this tomorrow.

**Comment by tglewis1993** [comment]
Software amirite?

Just tried manually creating the mods/as directory and issuing the make all... no luck.

There is no OpenRA.Mods.AS directory in the main OpenRA folder... should I try manually adding this directory too?

**Comment by GraionDilach** [comment]
Wait... what?

If you have followed the installation instructions, they clearly tell you to clone https://github.com/DoGyAUT/OpenRA which has OpenRA.Mods.AS. Now either you cloned a wrong branch there, either you assumed OpenRA/OpenRA would do, but that's not the case. In which case this is an user error.

**Comment by tglewis1993** [comment]
Yup this is a case of my bad, I'm using the the latest OpenRA bleed build not the one specified... Thanks for the help!
